name: Build and push image when new tag

on:
  push:
    tags: ['*']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: chenwei791129/.github/.github/workflows/build-and-push-image.yml@main
    with:
      dockerhub-repository: awei/kubectl
      build-args: |
        KUBE_VERSION=${{ github.ref_name }}
