name: Build and push image when new tag

on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      kubectl_version:
        description: 'kubectl version to build, example: v1.33.4'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: chenwei791129/.github/.github/workflows/build-and-push-image.yml@main
    with:
      dockerhub-repository: awei/kubectl
      enable-branch-tag: ${{ !inputs.kubectl_version }}
      enable-latest-tag: ${{ !inputs.kubectl_version }}
      additional-tags: |
        ${{ inputs.kubectl_version && format('type=semver,pattern={{{{version}}}},value={0}', inputs.kubectl_version) || '' }}
        ${{ inputs.kubectl_version && format('type=semver,pattern={{{{major}}}}.{{{{minor}}}},value={0}', inputs.kubectl_version) || '' }}
      build-args: |
        KUBECTL_VERSION=${{ inputs.kubectl_version || github.ref_name }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
